# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996247264ec7bf624c57c1823f4edd3d0582bbe5002aea538bf36fd61a061a3e869d0729989a0aa9a6dae9a2124f5811839f33925265a779b358e25f4dd6cd43

test:
  secret_key_base: a257a1fa0a237194a0ccc4fbfae7e002d45d9ed11be05988aed7ba41292fe01b2400363b27c0d401a0a7528f386746f47353cc10bfd8ff75df8e392e69c8d0f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
